name: Deploy CloudFormation Free-tier WordPress on EC2 with local MySQL

on:
  push:
    paths:
      - 'Free-tier WordPress on EC2 with local MySQL DB/Free-tier WordPress on EC2 with local MySQL'
  pull_request:
    paths:
      - 'Free-tier WordPress on EC2 with local MySQL DB/Free-tier WordPress on EC2 with local MySQL'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1   # change if needed

      # 3. Run CloudFormation deploy command
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file "Free-tier WordPress on EC2 with local MySQL DB/Free-tier WordPress on EC2 with local MySQL" \
            --stack-name my-stack1 \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              Env=Prod \
              InstanceType=t3.micro \
              KeyName=${{ secrets.EC2_KEY_NAME }}
